[workspace]
resolver = "2"
members = ["crates/cymose-core", "crates/cymose-cli"]

[workspace.package]
version = "0.1.0-beta.1"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/cymose/cymose-code"
rust-version = "1.85"

[workspace.dependencies]
cymose-core = { path = "crates/cymose-core" }
